services:
  # Adobe SDFS Application
  adobe:
    build: .
    container_name: Adobe
    volumes:
      - adobe_sdfs_storage:/app/adobe_sdfs_storage
    stdin_open: true
    tty: true

volumes:
  adobe_sdfs_storage: